### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by anbraten**
Updates the npm dependencies. Some of them had some reported vulnerabilities.

Hopefully this allows the CI to release properly.

### CODE REVIEW

**Comment by anbraten** [comment]
Checked it in a sample CI run on my fork and it seems to work / build now.

**Review by bondagit — APPROVED** [review]
ok

**Comment by bondagit** [comment]
I had to revert this because I cannot build the WebUI on Ubuntu 18.04 using the new packages

**Comment by bondagit** [comment]
All good. Thanks a lot for your effort !

**Pull request merged**
